version: '3.8'
services:
  db-badplay:
    image: postgres:15
    container_name: badplay-postgres
    environment:
      POSTGRES_USER: badplay_user
      POSTGRES_PASSWORD: badplay_password
      POSTGRES_DB: badplay_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio-badplay:
    image: minio/minio
    container_name: badplay-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin_minio
      MINIO_ROOT_PASSWORD: password_minio
    command: server /data --console-address ":9001"
    volumes:
      - miniodata:/data

volumes:
  pgdata:
  miniodata: