spring.datasource.url=jdbc:postgresql://localhost:5432/badplay_db
spring.datasource.username=badplay_user
spring.datasource.password=badplay_password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

minio.url=http://localhost:9000
minio.access.key=admin_minio
minio.access.secret=password_minio
minio.bucket.name=badplay-imagens

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

api.security.token.secret=MinhaChaveSuperSecretaBadPlayProjeto2026!@#