spring.datasource.url=jdbc:postgresql://localhost:5432/badplay_db
spring.datasource.username=badplay_user
spring.datasource.password=badplay_password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true